### ISSUE TITLE
GitLab checks if tests have passed on GitHub

### ISSUE THREAD

**Issue by SKairinos** [ocadotechnology/codeforlife-contributor-backend#28]
Check if the tests on the GitHub have passed for the production/staging/development branch before building and deploying.

Use the GH CLI:
- [gh run list](https://cli.github.com/manual/gh_run_list) to get latest run id
- [gh run watch](https://cli.github.com/manual/gh_run_watch) if latest run is still running

**Comment by faucomte97** [comment]
LGTM
